on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    
name: Mirror Github
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v4

    - name: Get Time
      id: get-time
      run: echo "date=$(/bin/date -u '+%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache src repos
      uses: actions/cache@v4
      id: cache
      with:
        path: ${{ github.workspace }}/hub-mirror-cache
        key: hub-repos-cache-github
        
    - name: Mirror with list
      uses: ./.
      with:
        src: git.techo.cool/poormonitor
        dst: github/poormonitor
        dst_key: ${{ secrets.PRIVATE_KEY }}
        dst_token:  ${{ secrets.GH_TOKEN }}
        cache_path: /github/workspace/hub-mirror-cache
        force_update: true
    
    - name: Print cache path
      run: |
        ls -la ${{ github.workspace }}/hub-mirror-cache
        
