on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    
name: Mirror Gitee
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
        
    - name: Mirror with white list
      uses: ./.
      with:
        src: github/poormonitor
        dst: gitee/poormonitor
        dst_key: ${{ secrets.PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        black_list: "hub-mirror-action"
        force_update: true
        
